export const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat semper viverra nam libero justo laoreet sit amet cursus. Ornare lectus sit amet est placerat in egestas erat. Ut eu sem integer vitae justo eget. Sodales neque sodales ut etiam sit amet nisl purus in. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Integer vitae justo eget magna fermentum. Donec et odio pellentesque diam. Enim tortor at auctor urna nunc id cursus metus. Vestibulum morbi blandit cursus risus. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Fringilla ut morbi tincidunt augue. Consequat nisl vel pretium lectus quam. Adipiscing elit ut aliquam purus sit amet. Amet massa vitae tortor condimentum lacinia. Morbi quis commodo odio aenean sed. Integer vitae justo eget magna. Commodo elit at imperdiet dui accumsan sit.



Vulputate dignissim suspendisse in est ante in nibh. In massa tempor nec feugiat. Neque volutpat ac tincidunt vitae semper quis. Hendrerit gravida rutrum quisque non tellus orci ac. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Amet porttitor eget dolor morbi non arcu risus quis. Nunc congue nisi vitae suscipit tellus mauris a. Lacinia quis vel eros donec ac. Eu non diam phasellus vestibulum lorem sed risus. At augue eget arcu dictum varius duis at. Leo in vitae turpis massa. Non quam lacus suspendisse faucibus. Quam adipiscing vitae proin sagittis. Mi bibendum neque egestas congue quisque egestas diam. Ornare arcu odio ut sem. Tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium. Ut etiam sit amet nisl purus. Dictum sit amet justo donec. Bibendum est ultricies integer quis auctor elit sed.


Sagittis vitae et leo duis ut diam. Auctor augue mauris augue neque gravida. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. At in tellus integer feugiat scelerisque varius morbi. Odio morbi quis commodo odio aenean. Feugiat in fermentum posuere urna nec. At imperdiet dui accumsan sit amet nulla facilisi. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Diam donec adipiscing tristique risus. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Orci nulla pellentesque dignissim enim sit amet. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales.

Ac feugiat sed lectus vestibulum mattis. A condimentum vitae sapien pellentesque. Egestas diam in arcu cursus euismod quis viverra nibh cras. Egestas integer eget aliquet nibh. Auctor urna nunc id cursus metus aliquam. Pharetra convallis posuere morbi leo. Nulla malesuada pellentesque elit eget gravida cum. A arcu cursus vitae congue mauris rhoncus. Purus non enim praesent elementum. Sit amet tellus cras adipiscing enim. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Quam lacus suspendisse faucibus interdum posuere lorem ipsum.`;
